spring:
  application:
    name: currency-conversion-service

server:
  port: 8100

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: ${currency-conversion-service.eureka.url:http://localhost:8761/eureka}
      
      
      
